# Site settings
title:       jayant jain
email:       jayantjain1992@gmail.com
author:      Jayant Jain
description: "Software Developer at Housing.com, Undergrad from IIT Roorkee"
url:         https://jayantj.github.io/
logo:         logo.png

# Google analytics
google_analytics: UA-75865966-1

# Facebook App ID
fb_app_id: 1732362650375679

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: jayantj

# Contact pane
contact_form: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    /:categories/:title
post_dirs: false
paginate:     5
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap